/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#FFF9ED",
        "surface-container-low": "#fbf3dc",
        "surface-container": "#f6eed6",
        "surface-container-high": "#f0e8d1",
        "surface-container-highest": "#eae2cb",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#E1DAC3",
        "surface": "#fff9ed",
        "surface-variant": "#eae2cb",
        "surface-tint": "#4b635c",
        "background": "#fff9ed",
        "forest-ink": "#1A2B27",
        "moss-border": "#D1DBCB",
        "primary": "#0e2520",
        "primary-container": "#243b35",
        "primary-fixed": "#cee8df",
        "primary-fixed-dim": "#b2ccc4",
        "on-primary": "#ffffff",
        "on-primary-container": "#8ca59d",
        "secondary": "#446554",
        "secondary-container": "#c3e8d2",
        "secondary-fixed": "#c6ebd5",
        "secondary-fixed-dim": "#aacfba",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#486a58",
        "tertiary": "#172515",
        "tertiary-container": "#2c3b29",
        "on-surface": "#1f1c0e",
        "on-surface-variant": "#424846",
        "outline": "#727876",
        "outline-variant": "#c2c8c4",
        "error": "#BA1A1A",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "status-verified": "#3F7658",
        "status-verified-soft": "#E7F0EA",
        "status-tampered": "#A8732A",
        "status-tampered-soft": "#F5EBDD",
        "status-invalid": "#BA1A1A",
        "status-invalid-soft": "#FFDAD6",
        "status-pending": "#526D8A",
        "status-pending-soft": "#E8EDF2",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      spacing: {
        "space-1": "0.25rem",
        "space-2": "0.5rem",
        "space-3": "0.75rem",
        "space-4": "1rem",
        "space-6": "1.5rem",
        "space-8": "2rem",
        "space-10": "2.5rem",
        "space-12": "3rem",
        "space-16": "4rem",
        "max-width": "90rem",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
